version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: meteologie
      - name: belgique
      - name: France

models:
  - name: stg_meteologie
    description: "Nettoyage et standardisation des données météo issues d'Airbyte"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null

  - name: int_meteologie
    description: "Préparation des données météo pour la dimension des stations"
    columns:
      - name: id
        tests:
          - not_null

  - name: dim_weather_stations
    description: "Dimension finale des stations météo amateurs et professionnelles"
    columns:
      - name: station_id
        tests:
          - not_null
          - unique

  - name: stg_stations_belgique
    description: "Données météo brutes de la station IICHTE19 (Belgique), nettoyées et enrichies."
    columns:
      - name: weather_station_id
        tests:
          - not_null
      - name: measurement_time
        tests:
          - not_null

  - name: stg_stations_france
    description: "Données météo brutes de la station ILAMAD25 (France), nettoyées et enrichies."
    columns:
      - name: weather_station_id
        tests:
          - not_null
      - name: measurement_time
        tests:
          - not_null
